// ============================================================
// PROPERTY INTEL — Apps Script v5.24 — FILE 6/7: plane.gs
// Plane pipeline: eligibility intake, v2 Stage A (/clip 3D
// models), Stage B (/render images), Pass 1 element pins + the
// Pass 1 rerun, Pass 2 concerns + descriptions, element review
// link, bounds backfill, Plane GitHub sync, and audits.
//
// v5.24: FOLDER-ONLY INDEX. processPlaneSheet merges ONLY views.plane onto
// data/index/{hash(site_no)}.json (indexHubId_). It never hashes Account Name
// as the hub filename. responder-drone record ids are not touched.
// v5.24 (catalog): fetchPinCatalog_ rewritten for the merged, TAGGED
// pins-catalog.json — takes accountType and returns elementNames/Ids +
// frConcernNames/Ids + wfConcernNames/Ids filtered by role/analysis/
// account_type (no id ranges). Plane Pass 1 uses elementNames/Ids; Plane
// Pass 2 uses frConcernNames/Ids. Dead validatePlanePins_ /
// splitPlanePinsBySection_ removed. Pass / pipeline logic is otherwise
// unchanged.
//
// v5.23 notes (Pass 2 — Stage 4, IN PROGRESS):
//   - fetchPinCatalog_ gained concernNames / concernIds (the
//     CONCERN-section vocabulary + id lookup), derived at runtime
//     from PIN_CONCERN_RANGES the same way the element subset is.
//     Cache key advanced to the v4 shape.
//   - validateConcernPins_: mirror of validateElementPins_ gated to
//     concern-section ids, so an element id can never leak into the
//     Nadir Concerns (S) column.
//   - planeRowReadyForPass2_: Pass 2 readiness — Elements Reviewed
//     (Q) === true AND Alpha Description (T) empty or ERROR. Q ALONE
//     gates Pass 2; R is irrelevant.
//   - (Next: runPass2Call_ / processPass2Row_ + active-row & batch
//     wrappers + menu items. Pass 2 writes S,T,U,V,W,X,Y and never
//     touches P, Q, or R — approved element pins are frozen.)
//
// v5.22 notes:
//   - runElementPinsCall_ extracted as the shared core for Pass 1
//     AND the rerun (image fetch loop, Bedrock call, parse,
//     validateElementPins_, write Nadir Elements (P), reset
//     Elements Reviewed (Q)). processElementPinsRow_ is now a thin
//     Pass 1 wrapper.
//   - PASS 1 RERUN (Option C — text coordinates, no Lambda):
//     rerunElementPinsRow_ / rerunElementPinsForActiveRow /
//     rerunElementPinsBatch. The rerun re-sends the five clean
//     images plus the current pins as named text (currentPinsAsText_)
//     and the analyst's Nadir Fixes (R) note, and re-emits corrected
//     element pins. It rewrites P and resets Q; it NEVER writes R.
//     Batch selector: R non-empty AND Q unchecked. This-Row: ignores
//     Q, requires a non-empty R. Q ALONE gates Pass 2 — R is
//     irrelevant to it.
//   - fetchPinCatalog_ gained namesList and its cache key advanced to
//     the v3 shape.
//
// v5.20 remap notes:
//   - All reads/writes use the NEW 27-column layout (config.gs).
//   - Stage C interim: still ONE full-catalog Bedrock call, but
//     validated pins are section-split on write — element ids to
//     Nadir Elements (P), concern ids to Nadir Concerns (S).
//     True two-pass (element-only Pass 1, reviewed-gated Pass 2)
//     lands in later stages.
//   - Commercial rows now use the residential pin catalog as a
//     placeholder (per design lock). The free-vocabulary
//     commercial pin branch is removed; legacy commercial
//     {label,x,y} pins were parked verbatim in Nadir Elements by
//     the migration and will be regenerated by Pass 1.
//   - v1 imagery functions removed (v1 Lambda writes to OLD
//     column positions — must never fire against this layout).
// ============================================================

// ============================================================
// PLANE PIPELINE — STAGE 1: ELIGIBILITY INTAKE
// ============================================================
// Reads every property on the Satellite sheet, checks each against
// real 2D plane-capture coverage via the plane-eligibility-check
// Lambda (batched — one HTTP call per ELIGIBILITY_BATCH_SIZE rows),
// and appends every ELIGIBLE property to the Plane sheet.
// Never duplicates: addresses already on the Plane sheet are skipped.

function checkPlaneEligibility() {
  const ss = SpreadsheetApp.getActiveSpreadsheet();
  const satSheet   = ss.getSheetByName(SATELLITE_SHEET);
  const planeSheet = ss.getSheetByName(PLANE_SHEET);
  if (!satSheet)   { SpreadsheetApp.getUi().alert('Sheet "' + SATELLITE_SHEET + '" not found'); return; }
  if (!planeSheet) { SpreadsheetApp.getUi().alert('Sheet "' + PLANE_SHEET + '" not found'); return; }

  // 1. Collect Satellite candidates (skip header), excluding properties
  //    already on the Plane sheet.
  const satData  = satSheet.getDataRange().getValues();
  const existing = getExistingPlaneAddresses_(planeSheet);

  const candidates = [];
  let skippedExisting = 0;
  for (let i = 1; i < satData.length; i++) {
    const address = String(satData[i][SAT_COL_ADDRESS - 1] || '').trim();
    if (!address) continue;
    if (existing[normalizePlaneAddress_(address)]) { skippedExisting++; continue; }
    candidates.push({
      satRow:      i + 1,  // 1-indexed row; echoes back from the Lambda as rowIndex
      accountType: normalizeAccountType(satData[i][SAT_COL_ACCOUNT_TYPE - 1]),
      accountName: String(satData[i][SAT_COL_ACCOUNT - 1] || '').trim(),
      address:     address,
      hoa:         String(satData[i][SAT_COL_HOA - 1] || '').trim(),
      siteNo:      satValidSiteNo_(satData[i][SAT_COL_SITE_NO - 1])
    });
  }

  if (!candidates.length) {
    SpreadsheetApp.getUi().alert('Plane Eligibility',
      'No new properties to check.\n(' + skippedExisting + ' already on the Plane sheet.)',
      SpreadsheetApp.getUi().ButtonSet.OK);
    return;
  }

  // 2. Batched eligibility calls.
  const byRow = {};
  candidates.forEach(c => { byRow[c.satRow] = c; });

  const eligible = [];
  const ineligible = [];
  for (let i = 0; i < candidates.length; i += ELIGIBILITY_BATCH_SIZE) {
    const batch = candidates.slice(i, i + ELIGIBILITY_BATCH_SIZE)
      .map(c => ({ rowIndex: c.satRow, address: c.address }));
    const results = callPlaneEligibility_(batch);
    results.forEach(res => {
      const cand = byRow[res.rowIndex];
      if (!cand) return;
      if (res.eligible) { cand.taxlot = res.taxlot; eligible.push(cand); }
      else { ineligible.push({ address: cand.address, reason: res.reason }); }
    });
  }

  // 3. Append eligible properties to the Plane sheet in one batch write.
  //    New layout: A Account Type, B Property Name, C Address, D HOA,
  //    E Taxlot (persisted right away when the Lambda returned one).
  if (eligible.length) {
    const width = Math.max(planeSheet.getLastColumn(), PLANE_COL_SITE_NO);
    const rows = eligible.map(c => {
      const row = new Array(width).fill('');
      row[PLANE_COL_ACCOUNT_TYPE - 1] = c.accountType;
      row[PLANE_COL_ACCOUNT - 1]      = c.accountName;
      row[PLANE_COL_ADDRESS - 1]      = c.address;
      row[PLANE_COL_HOA - 1]          = c.hoa;
      if (c.taxlot) row[PLANE_COL_TAXLOT - 1] = String(c.taxlot);
      if (c.siteNo) row[PLANE_COL_SITE_NO - 1] = c.siteNo;
      return row;
    });
    planeSheet.getRange(planeSheet.getLastRow() + 1, 1, rows.length, width).setValues(rows);
  }

  // 4. Operator summary; full ineligible detail in execution logs.
  const lines = [
    'Checked: ' + candidates.length,
    'Added to Plane sheet: ' + eligible.length,
    'Ineligible: ' + ineligible.length,
    'Skipped (already on Plane sheet): ' + skippedExisting
  ];
  if (ineligible.length) {
    lines.push('', 'Ineligible details:');
    ineligible.slice(0, 15).forEach(x => lines.push('• ' + x.address + ' — ' + x.reason));
    if (ineligible.length > 15) lines.push('…and ' + (ineligible.length - 15) + ' more (see execution logs)');
    ineligible.forEach(x => Logger.log('INELIGIBLE: ' + x.address + ' — ' + x.reason));
  }
  SpreadsheetApp.getUi().alert('Plane Eligibility', lines.join('\n'),
                               SpreadsheetApp.getUi().ButtonSet.OK);
}

// One batched POST to the eligibility Lambda.
// Contract: {"addresses":[{"rowIndex":N,"address":"..."}]}
//        -> {"results":[{"rowIndex":N,"eligible":bool,"taxlot":str|null,"reason":str}]}
function callPlaneEligibility_(batch) {
  const response = UrlFetchApp.fetch(PLANE_API_BASE + '/eligibility', {
    method: 'post',
    contentType: 'application/json',
    payload: JSON.stringify({ addresses: batch }),
    muteHttpExceptions: true
  });
  const code = response.getResponseCode();
  const text = response.getContentText();
  if (code !== 200) throw new Error('Eligibility check failed (HTTP ' + code + '): ' + text);
  const parsed = JSON.parse(text);
  if (parsed.results) return parsed.results;                       // API GW proxy, unwrapped
  if (parsed.body) return JSON.parse(parsed.body).results || [];   // direct-invoke shape
  throw new Error('Unexpected eligibility response: ' + text.substring(0, 300));
}

// Map of normalized address -> true for every row already on the Plane sheet.
function getExistingPlaneAddresses_(planeSheet) {
  const out = {};
  const lastRow = planeSheet.getLastRow();
  if (lastRow < 2) return out;
  planeSheet.getRange(2, PLANE_COL_ADDRESS, lastRow - 1, 1).getValues().forEach(row => {
    const a = normalizePlaneAddress_(String(row[0] || ''));
    if (a) out[a] = true;
  });
  return out;
}

// Case/whitespace/punctuation-insensitive address key for dedupe.
function normalizePlaneAddress_(address) {
  return address.toLowerCase().replace(/[.,#]/g, '').replace(/\s+/g, ' ').trim();
}

// ── PLANE PIPELINE v2 — STORYBOARD (Layer 3) ──────────────────────────────
// Sibling stage to Images/Pass 1/Pass 2. For each row with a taxlot + coords
// + a cached GLB, calls plane-parcel-render with {storyboard:true} (the
// prepare_render-only branch — no render), stores {alpha,ent_x,ent_y} in the
// Storyboard column (AB), and rebuilds the 360 View URL (O) to the new
// model-viewer.html with those params baked in. Sync Plane then publishes O as
// viewer360, so the client's plane tab launches the storyboard viewer.
function buildStoryboardViewerUrl_(glbUrl, alpha, entX, entY) {
  let url = V2_VIEWER_BASE + glbUrl + '&alpha=' + alpha;
  if (entX !== null && entX !== undefined && entY !== null && entY !== undefined) {
    url += '&ent_x=' + entX + '&ent_y=' + entY;
  }
  return url;
}

function planeRowReadyForStoryboard_(rowVals) {
  const taxlot = String(rowVals[PLANE_COL_TAXLOT - 1] || '').trim();
  const lat = parseFloat(rowVals[PLANE_COL_LAT - 1]);
  const lng = parseFloat(rowVals[PLANE_COL_LNG - 1]);
  if (!taxlot || isNaN(lat) || isNaN(lng)) return false;
  const sb = String(rowVals[PLANE_COL_STORYBOARD - 1] || '').trim();
  return !sb || sb.indexOf('ERROR:') === 0;
}

function processStoryboardRow_(sheet, row) {
  const taxlot  = String(sheet.getRange(row, PLANE_COL_TAXLOT).getValue() || '').trim();
  const address = String(sheet.getRange(row, PLANE_COL_ADDRESS).getValue() || '').trim();
  const lat = parseFloat(sheet.getRange(row, PLANE_COL_LAT).getValue());
  const lng = parseFloat(sheet.getRange(row, PLANE_COL_LNG).getValue());
  if (!taxlot || isNaN(lat) || isNaN(lng)) {
    sheet.getRange(row, PLANE_COL_V2_STATUS)
         .setValue('storyboard SKIPPED: needs taxlot + coords (run Generate 3D Models first)');
    return false;
  }
  const payload = { storyboard: true, taxlot: taxlot, lat: lat, lng: lng,
                    address: address, rowIndex: row };
  let res = callV2_('/render', payload);
  if (!res.ok && (res.code === 504 || res.code === 502 || /tim(ed)? ?out|gateway/i.test(res.error || ''))) {
    Logger.log('storyboard: first call timed out (likely cold render Lambda) -- retrying once on warm Lambda');
    Utilities.sleep(2000);
    res = callV2_('/render', payload);
  }
  const body = res.body;
  if (res.code !== 200 || !body || !body.ok) {
    sheet.getRange(row, PLANE_COL_V2_STATUS)
         .setValue('storyboard FAILED: ' + ((body && body.reason) || ('HTTP ' + res.code)));
    return false;
  }
  writePlainCell(sheet, row, PLANE_COL_STORYBOARD,
    JSON.stringify({ alpha: body.alpha, ent_x: body.ent_x, ent_y: body.ent_y }));
  sheet.getRange(row, V2_VIEWER_COL)
       .setValue(buildStoryboardViewerUrl_(body.glb_url, body.alpha, body.ent_x, body.ent_y));
  const entTxt = (body.ent_x === null || body.ent_x === undefined)
    ? 'no entrance point (tier 3/4)' : 'ent=(' + body.ent_x + ',' + body.ent_y + ')';
  sheet.getRange(row, PLANE_COL_V2_STATUS)
       .setValue('storyboard done (alpha=' + body.alpha + ', ' + entTxt + ')');
  return true;
}

function generateStoryboardV2() {
  const sheet = SpreadsheetApp.getActiveSpreadsheet().getSheetByName(PLANE_SHEET);
  if (!sheet) { SpreadsheetApp.getUi().alert('Sheet "' + PLANE_SHEET + '" not found'); return; }
  ensureV2Headers_(sheet);
  const lastRow = sheet.getLastRow();
  if (lastRow < 2) { SpreadsheetApp.getUi().alert('Plane sheet is empty.'); return; }
  const width = Math.max(sheet.getLastColumn(), PLANE_COL_STORYBOARD);
  const data  = sheet.getRange(2, 1, lastRow - 1, width).getValues();

  const readyRows = [];
  data.forEach(function (r, i) {
    const address = String(r[PLANE_COL_ADDRESS - 1] || '').trim();
    if (address && planeRowReadyForStoryboard_(r)) readyRows.push(i + 2);
  });
  if (!readyRows.length) {
    SpreadsheetApp.getUi().alert('Plane Storyboard',
      'No rows ready.\n(A row is ready when it has a Taxlot + coords and the Storyboard cell is empty. Run Generate 3D Models first.)',
      SpreadsheetApp.getUi().ButtonSet.OK);
    return;
  }
  let done = 0, failed = 0, attempted = 0;
  for (let i = 0; i < readyRows.length; i++) {
    if (attempted >= BATCH_SIZE) break;
    attempted++;
    try { if (processStoryboardRow_(sheet, readyRows[i])) done++; else failed++; }
    catch (e) {
      failed++;
      Logger.log('Storyboard ERROR row ' + readyRows[i] + ': ' + e.message);
      sheet.getRange(readyRows[i], PLANE_COL_V2_STATUS).setValue('storyboard FAILED: ' + e.message.substring(0, 80));
    }
    Utilities.sleep(1000);
  }
  const remaining = readyRows.length - attempted + failed;
  SpreadsheetApp.getUi().alert('Plane Storyboard',
    'Completed: ' + done + '\nFailed: ' + failed +
    (remaining > 0 ? '\nRemaining: ' + remaining + ' — run again to continue.' : '\nAll ready rows processed.') +
    (done > 0 ? '\n\nThe 360 View URL now points at the storyboard viewer. Run "Sync Plane" to publish.' : ''),
    SpreadsheetApp.getUi().ButtonSet.OK);
}

function generateStoryboardForActiveRow() {
  const ss = SpreadsheetApp.getActiveSpreadsheet();
  const sheet = ss.getSheetByName(PLANE_SHEET);
  if (!sheet) { SpreadsheetApp.getUi().alert('Sheet "' + PLANE_SHEET + '" not found'); return; }
  if (ss.getActiveSheet().getName() !== PLANE_SHEET) {
    SpreadsheetApp.getUi().alert('Please select a row on the "' + PLANE_SHEET + '" sheet.'); return;
  }
  const row = sheet.getActiveCell().getRow();
  if (row < 2) { SpreadsheetApp.getUi().alert('Please select a data row.'); return; }
  const address = String(sheet.getRange(row, PLANE_COL_ADDRESS).getValue() || '').trim();
  if (!address) { SpreadsheetApp.getUi().alert('Row ' + row + ' has no Property Address.'); return; }
  const existing = String(sheet.getRange(row, PLANE_COL_STORYBOARD).getValue() || '').trim();
  if (existing && existing.indexOf('ERROR:') !== 0) {
    const ui = SpreadsheetApp.getUi();
    const ans = ui.alert('Regenerate?',
      'Row ' + row + ' already has storyboard data.\nRegenerate for:\n' + address + '?',
      ui.ButtonSet.YES_NO);
    if (ans !== ui.Button.YES) return;
  }
  const ok = processStoryboardRow_(sheet, row);
  SpreadsheetApp.getUi().alert('Plane Storyboard',
    ok ? 'Storyboard written for:\n' + address + '\n\nThe 360 View URL now points at the storyboard viewer. Run "Sync Plane" to publish.'
       : 'Storyboard generation FAILED for:\n' + address + '\nSee the v2 Status column and execution logs.',
    SpreadsheetApp.getUi().ButtonSet.OK);
}

// ============================================================
// PLANE PIPELINE v2 — 3D MODELS + PROPERTY IMAGES
// ============================================================
// Wired to the v2 factory: plane-parcel-clip (/clip) and
// plane-parcel-render (/render). API Gateway cuts every call at
// 29 s but the Lambda keeps running, so both stages are
// async-and-poll on 1-minute triggers with state in Script
// Properties:
//   Stage A (/clip)  — cache-idempotent, so the SAME batch is
//     re-POSTed until it returns 200 all-cached (convergent poll).
//   Stage B (/render) — fired with {async:true} (self-dispatch,
//     202) and polled with {probe:true} (pure S3 status check,
//     zero side effects — never re-renders).

// POST to a v2 route; parses both proxy and direct-invoke shapes.
function callV2_(path, payload) {
  const res = UrlFetchApp.fetch(PLANE_API_BASE + path, {
    method: 'post', contentType: 'application/json',
    payload: JSON.stringify(payload), muteHttpExceptions: true
  });
  const code = res.getResponseCode();
  let body = null;
  try {
    body = JSON.parse(res.getContentText());
    if (body && typeof body.body === 'string') body = JSON.parse(body.body);
  } catch (e) {}
  return { code: code, body: body };
}

function ensureV2Headers_(sheet) {
  const headers = [[PLANE_COL_TAXLOT, 'Taxlot'], [PLANE_COL_LAT, 'Lat'],
                   [PLANE_COL_LNG, 'Lng'],
                   [PLANE_COL_NADIR_BOUNDS, 'Nadir Bounds'],
                   [PLANE_COL_ELEMENTS, 'Nadir Elements'],
                   [PLANE_COL_REVIEWED, 'Elements Reviewed'],
                   [PLANE_COL_FIXES, 'Nadir Fixes'],
                   [PLANE_COL_CONCERNS_P, 'Nadir Concerns'],
                   [PLANE_COL_V2_STATUS, 'v2 Status'],
                   [PLANE_COL_STORYBOARD, 'Storyboard']];
  headers.forEach(function (h) {
    const cell = sheet.getRange(1, h[0]);
    if (!String(cell.getValue() || '').trim()) cell.setValue(h[1]);
  });
}

function setV2Trigger_(handler) {
  clearV2Trigger_(handler);
  ScriptApp.newTrigger(handler).timeBased().everyMinutes(1).create();
}

function clearV2Trigger_(handler) {
  ScriptApp.getProjectTriggers().forEach(function (t) {
    if (t.getHandlerFunction() === handler) ScriptApp.deleteTrigger(t);
  });
}

function cancelV2Jobs() {
  clearV2Trigger_('pollClipV2_');
  clearV2Trigger_('imagesTickV2_');
  const props = PropertiesService.getScriptProperties();
  props.deleteProperty('planeClipJobV2');
  props.deleteProperty('planeImgJobV2');
  SpreadsheetApp.getActiveSpreadsheet().toast('v2 jobs cancelled.');
}

function checkV2JobStatus() {
  const props = PropertiesService.getScriptProperties();
  const clip = props.getProperty('planeClipJobV2');
  const img  = props.getProperty('planeImgJobV2');
  const lines = [];
  if (clip) {
    const j = JSON.parse(clip);
    lines.push('3D Models: generating (' + j.batch.properties.length +
               ' rows, poll ' + j.polls + '/' + V2_MAX_POLLS + ')');
  } else lines.push('3D Models: no job running');
  if (img) {
    const j = JSON.parse(img);
    const c = { pending: 0, fired: 0, done: 0, error: 0 };
    j.items.forEach(function (it) { c[it.state] = (c[it.state] || 0) + 1; });
    lines.push('Images: pending ' + c.pending + ', rendering ' + c.fired +
               ', done ' + c.done + ', error ' + c.error);
  } else lines.push('Images: no job running');
  SpreadsheetApp.getUi().alert('v2 Job Status', lines.join('\n'),
                               SpreadsheetApp.getUi().ButtonSet.OK);
}

// ── v2 STAGE A — GENERATE 3D MODELS ─────────────────────────
// For every Plane row with an address: resolve taxlot + coords
// (batched /eligibility, geocode fallback; persisted to E/F/G),
// then convergent-poll /clip until every parcel's GLB is cached.
// Writes the 3D viewer link to column O.

function generate3DModelsV2() {
  const sheet = SpreadsheetApp.getActiveSpreadsheet().getSheetByName(PLANE_SHEET);
  if (!sheet) { SpreadsheetApp.getUi().alert('Sheet "' + PLANE_SHEET + '" not found'); return; }
  ensureV2Headers_(sheet);

  const lastRow = sheet.getLastRow();
  if (lastRow < 2) { SpreadsheetApp.getUi().alert('Plane sheet is empty.'); return; }
  const width = Math.max(sheet.getLastColumn(), PLANE_COL_LNG);
  const data = sheet.getRange(2, 1, lastRow - 1, width).getValues();

  // 1. Resolve taxlot (+ coords) for rows that lack one.
  const rows = [];
  const needTaxlot = [];
  const byRow = {};
  data.forEach(function (r, i) {
    const address = String(r[PLANE_COL_ADDRESS - 1] || '').trim();
    if (!address) return;
    const row = i + 2;
    const item = { row: row, address: address,
                   taxlot: String(r[PLANE_COL_TAXLOT - 1] || '').trim() };
    rows.push(item);
    byRow[row] = item;
    if (!item.taxlot) needTaxlot.push({ rowIndex: row, address: address });
  });
  if (!rows.length) { SpreadsheetApp.getUi().alert('No Plane rows with an address.'); return; }

  for (let i = 0; i < needTaxlot.length; i += V2_ELIG_BATCH) {
      const chunk = needTaxlot.slice(i, i + V2_ELIG_BATCH);
      let results;
      try {
        results = callPlaneEligibility_(chunk);
      } catch (e) {
        Logger.log('v2 eligibility chunk failed (' + e.message + ') — retrying once on warm Lambda');
        Utilities.sleep(2000);
        try {
          results = callPlaneEligibility_(chunk);
        } catch (e2) {
          chunk.forEach(function (c) {
            sheet.getRange(c.rowIndex, PLANE_COL_V2_STATUS)
                .setValue('taxlot lookup FAILED: ' + e2.message.substring(0, 80));
          });
          continue;
        }
      }
      results.forEach(function (res) {
      const r = byRow[res.rowIndex];
      if (!r) return;
      if (res.eligible && res.taxlot) {
        r.taxlot = String(res.taxlot);
        sheet.getRange(r.row, PLANE_COL_TAXLOT).setValue(r.taxlot);
        if (res.lat && res.lng) {
          sheet.getRange(r.row, PLANE_COL_LAT).setValue(res.lat);
          sheet.getRange(r.row, PLANE_COL_LNG).setValue(res.lng);
        }
      } else {
        sheet.getRange(r.row, PLANE_COL_V2_STATUS)
             .setValue('not eligible: ' + (res.reason || '?'));
      }
    });
  }
  // Geocode fallback for coordinates (Stage B needs them).
  rows.forEach(function (r) {
    if (!r.taxlot) return;
    const lat = parseFloat(sheet.getRange(r.row, PLANE_COL_LAT).getValue());
    if (!isNaN(lat)) return;
    const c = geocodeAddress(r.address);
    if (c) {
      sheet.getRange(r.row, PLANE_COL_LAT).setValue(c.lat);
      sheet.getRange(r.row, PLANE_COL_LNG).setValue(c.lng);
    }
  });

  const props = rows.filter(function (r) { return r.taxlot; })
    .map(function (r) {
      const p = { rowIndex: r.row, taxlot: r.taxlot };
      const lat = parseFloat(sheet.getRange(r.row, PLANE_COL_LAT).getValue());
      const lng = parseFloat(sheet.getRange(r.row, PLANE_COL_LNG).getValue());
      if (!isNaN(lat) && !isNaN(lng)) { p.lat = lat; p.lng = lng; }
      return p;
    });
  if (!props.length) {
    SpreadsheetApp.getUi().alert('No eligible rows with a taxlot — see the v2 Status column.');
    return;
  }

  // 2. Convergent /clip: 200 now, or a 1-minute trigger until cached.
  const batch = { properties: props };
  const res = callV2_('/clip', batch);
  if (res.code === 200 && res.body && res.body.results) {
    writeClipResultsV2_(sheet, res.body.results);
    SpreadsheetApp.getActiveSpreadsheet().toast(
      '3D models: complete (' + res.body.results.length + ' rows).');
    return;
  }
  PropertiesService.getScriptProperties().setProperty('planeClipJobV2',
    JSON.stringify({ batch: batch, polls: 0 }));
  setV2Trigger_('pollClipV2_');
  props.forEach(function (p) {
    sheet.getRange(p.rowIndex, PLANE_COL_V2_STATUS).setValue('generating 3D model...');
  });
  SpreadsheetApp.getActiveSpreadsheet().toast(
    '3D models: generating ' + props.length + ' — checking every minute; ' +
    'viewer links will appear in column O automatically.');
}

function pollClipV2_() {
  const propsSvc = PropertiesService.getScriptProperties();
  const raw = propsSvc.getProperty('planeClipJobV2');
  if (!raw) { clearV2Trigger_('pollClipV2_'); return; }
  const job = JSON.parse(raw);
  const sheet = SpreadsheetApp.getActiveSpreadsheet().getSheetByName(PLANE_SHEET);
  const res = callV2_('/clip', job.batch);
  if (res.code === 200 && res.body && res.body.results) {
    writeClipResultsV2_(sheet, res.body.results);
    propsSvc.deleteProperty('planeClipJobV2');
    clearV2Trigger_('pollClipV2_');
    SpreadsheetApp.getActiveSpreadsheet().toast('3D models: complete.');
    return;
  }
  job.polls += 1;
  if (job.polls >= V2_MAX_POLLS) {
    propsSvc.deleteProperty('planeClipJobV2');
    clearV2Trigger_('pollClipV2_');
    job.batch.properties.forEach(function (p) {
      sheet.getRange(p.rowIndex, PLANE_COL_V2_STATUS)
           .setValue('3D model TIMED OUT — check CloudWatch (plane-parcel-clip)');
    });
    return;
  }
  propsSvc.setProperty('planeClipJobV2', JSON.stringify(job));
}

function writeClipResultsV2_(sheet, results) {
  results.forEach(function (r) {
    if (!r.rowIndex) return;
    if (r.ok) {
      sheet.getRange(r.rowIndex, V2_VIEWER_COL).setValue(V2_VIEWER_BASE + r.glb_url);
      sheet.getRange(r.rowIndex, PLANE_COL_V2_STATUS)
           .setValue('3D model ' + r.status + ' (' + (r.capture || '') + ')');
    } else {
      sheet.getRange(r.rowIndex, PLANE_COL_V2_STATUS)
           .setValue('3D model FAILED: ' + (r.reason || '?'));
    }
  });
}

// ── v2 — FORCE-REGENERATE 3D MODELS ─────────────────────────
// Purges the cached GLB(s) in S3 (+ CloudFront invalidation) via the
// /clip purge action, clears the row's stale outputs (images, bounds,
// viewer link, elements, fixes, concerns, descriptions), resets the
// review checkbox, then starts the normal convergent clip job. Purge
// is one-shot; the poll loop only ever re-sends the plain generate
// batch, so fresh GLBs are never deleted.

function regeneratePlaneModelForActiveRow() {
  const ss = SpreadsheetApp.getActiveSpreadsheet();
  const sheet = ss.getSheetByName(PLANE_SHEET);
  if (!sheet) { SpreadsheetApp.getUi().alert('Sheet "' + PLANE_SHEET + '" not found'); return; }
  if (ss.getActiveSheet().getName() !== PLANE_SHEET) {
    SpreadsheetApp.getUi().alert('Please select a row on the "' + PLANE_SHEET + '" sheet.');
    return;
  }
  const row = sheet.getActiveCell().getRow();
  if (row < 2) { SpreadsheetApp.getUi().alert('Please select a data row.'); return; }
  regeneratePlaneModels_(sheet, [row]);
}

function regeneratePlaneModelsForSelectedRows() {
  const ss = SpreadsheetApp.getActiveSpreadsheet();
  const sheet = ss.getSheetByName(PLANE_SHEET);
  if (!sheet) { SpreadsheetApp.getUi().alert('Sheet "' + PLANE_SHEET + '" not found'); return; }
  if (ss.getActiveSheet().getName() !== PLANE_SHEET) {
    SpreadsheetApp.getUi().alert('Please select rows on the "' + PLANE_SHEET + '" sheet.');
    return;
  }
  const range = sheet.getActiveRange();
  const rows = [];
  for (let r = range.getRow(); r < range.getRow() + range.getNumRows(); r++) {
    if (r >= 2) rows.push(r);
  }
  if (!rows.length) { SpreadsheetApp.getUi().alert('Please select data rows.'); return; }
  regeneratePlaneModels_(sheet, rows);
}

function regeneratePlaneModels_(sheet, rowNumbers) {
  const ui = SpreadsheetApp.getUi();

  // 1. Collect items — taxlot required (regenerate implies a prior clip).
  const items = [];
  const skipped = [];
  rowNumbers.forEach(function (row) {
    const address = String(sheet.getRange(row, PLANE_COL_ADDRESS).getValue() || '').trim();
    const taxlot  = String(sheet.getRange(row, PLANE_COL_TAXLOT).getValue() || '').trim();
    if (!address || !taxlot) { skipped.push(row); return; }
    const item = { rowIndex: row, taxlot: taxlot, address: address };
    const lat = parseFloat(sheet.getRange(row, PLANE_COL_LAT).getValue());
    const lng = parseFloat(sheet.getRange(row, PLANE_COL_LNG).getValue());
    if (!isNaN(lat) && !isNaN(lng)) { item.lat = lat; item.lng = lng; }
    items.push(item);
  });
  if (!items.length) {
    ui.alert('Regenerate 3D Models',
      'No eligible rows selected.\n(A row needs an address and a Taxlot in column E — run Generate 3D Models (v2) first for brand-new rows.)',
      ui.ButtonSet.OK);
    return;
  }

  // 2. Confirm — this is destructive.
  const answer = ui.alert('Regenerate 3D Models',
    'This deletes the cached 3D model(s) in S3 and clears images, pins, descriptions, and the viewer link for:\n\n• ' +
    items.map(function (it) { return it.address; }).join('\n• ') +
    '\n\nThen fresh models are generated. Continue?',
    ui.ButtonSet.YES_NO);
  if (answer !== ui.Button.YES) return;

  // 3. Purge the S3 cache (+ CloudFront invalidation) — one-shot call.
  const purgeItems = items.map(function (it) {
    return { rowIndex: it.rowIndex, taxlot: it.taxlot };
  });
  const purgeRes = callV2_('/clip', { purge: true, properties: purgeItems });
  if (purgeRes.code !== 200 || !purgeRes.body || !purgeRes.body.purged) {
    ui.alert('Regenerate 3D Models',
      'Cache purge FAILED (HTTP ' + purgeRes.code + ') — aborting before clearing any data.\nSee CloudWatch (plane-parcel-clip).',
      ui.ButtonSet.OK);
    return;
  }

  // 4. Clear stale row outputs on the NEW layout:
  //    I–P (9–16): image URLs, nadir bounds, 360 viewer link, elements.
  //    R–Y (18–25): fixes, concerns, oblique descriptions, considerations,
  //    clarifications. Reset the Elements Reviewed checkbox (Q/17) to
  //    unchecked. FR Link (Z) is left; the next Sync Plane refreshes it.
  items.forEach(function (it) {
    sheet.getRange(it.rowIndex, PLANE_COL_NADIR_URL, 1,
                   PLANE_COL_ELEMENTS - PLANE_COL_NADIR_URL + 1).clearContent();
    sheet.getRange(it.rowIndex, PLANE_COL_FIXES, 1,
                   PLANE_COL_CLARIFY - PLANE_COL_FIXES + 1).clearContent();
    sheet.getRange(it.rowIndex, PLANE_COL_REVIEWED).setValue(false);
    sheet.getRange(it.rowIndex, PLANE_COL_V2_STATUS).setValue('regenerating 3D model...');
  });
  SpreadsheetApp.flush();

  // 5. Start the normal convergent clip job (fresh generation — cache is gone).
  const props = items.map(function (it) {
    const p = { rowIndex: it.rowIndex, taxlot: it.taxlot };
    if (it.lat !== undefined) { p.lat = it.lat; p.lng = it.lng; }
    return p;
  });
  const batch = { properties: props };
  const res = callV2_('/clip', batch);
  if (res.code === 200 && res.body && res.body.results) {
    writeClipResultsV2_(sheet, res.body.results);
    SpreadsheetApp.getActiveSpreadsheet().toast(
      'Regenerated ' + res.body.results.length + ' model(s).' +
      (skipped.length ? ' Skipped ' + skipped.length + ' row(s) without a taxlot.' : ''));
    return;
  }
  PropertiesService.getScriptProperties().setProperty('planeClipJobV2',
    JSON.stringify({ batch: batch, polls: 0 }));
  setV2Trigger_('pollClipV2_');
  SpreadsheetApp.getActiveSpreadsheet().toast(
    'Regenerating ' + props.length + ' model(s) — checking every minute; ' +
    'viewer links will appear in column O automatically.' +
    (skipped.length ? ' Skipped ' + skipped.length + ' row(s) without a taxlot.' : ''));
}

// ── v2 STAGE B — GENERATE PROPERTY IMAGES ───────────────────
// Requires Stage A first (taxlot in E, coords in F/G, cached GLB).
// Fires each render async (202), probes each minute with zero side
// effects, writes the five image URLs into I/K/L/M/N per property
// and the nadir bounds JSON into J.

function generateImagesV2() {
  const sheet = SpreadsheetApp.getActiveSpreadsheet().getSheetByName(PLANE_SHEET);
  if (!sheet) { SpreadsheetApp.getUi().alert('Sheet "' + PLANE_SHEET + '" not found'); return; }
  ensureV2Headers_(sheet);

  const lastRow = sheet.getLastRow();
  if (lastRow < 2) { SpreadsheetApp.getUi().alert('Plane sheet is empty.'); return; }
  const width = Math.max(sheet.getLastColumn(), PLANE_COL_LNG);
  const data = sheet.getRange(2, 1, lastRow - 1, width).getValues();

  const items = [];
  let skipped = 0;
  data.forEach(function (r, i) {
    const row = i + 2;
    const address = String(r[PLANE_COL_ADDRESS - 1] || '').trim();
    if (!address) return;
    const taxlot = String(r[PLANE_COL_TAXLOT - 1] || '').trim();
    const lat = parseFloat(r[PLANE_COL_LAT - 1]);
    const lng = parseFloat(r[PLANE_COL_LNG - 1]);
    if (!taxlot || isNaN(lat) || isNaN(lng)) { skipped++; return; }
    items.push({ row: row, taxlot: taxlot, lat: lat, lng: lng,
                 address: address, state: 'pending', polls: 0 });
  });
  if (!items.length) {
    SpreadsheetApp.getUi().alert('No rows ready. Run "Generate 3D Models (v2)" first' +
      (skipped ? ' (' + skipped + ' rows missing taxlot/coords).' : '.'));
    return;
  }
  PropertiesService.getScriptProperties().setProperty('planeImgJobV2',
    JSON.stringify({ items: items }));
  setV2Trigger_('imagesTickV2_');
  SpreadsheetApp.getActiveSpreadsheet().toast(
    'Images: queued ' + items.length + ' properties (' + V2_FIRE_PER_TICK +
    '/minute). URLs will fill in as renders finish (~90 s each).');
  imagesTickV2_();
}

function imagesTickV2_() {
  const propsSvc = PropertiesService.getScriptProperties();
  const raw = propsSvc.getProperty('planeImgJobV2');
  if (!raw) { clearV2Trigger_('imagesTickV2_'); return; }
  const job = JSON.parse(raw);
  const sheet = SpreadsheetApp.getActiveSpreadsheet().getSheetByName(PLANE_SHEET);

  let fired = 0;
  job.items.forEach(function (it) {
    if (it.state === 'pending' && fired < V2_FIRE_PER_TICK) {
      const res = callV2_('/render', { taxlot: it.taxlot, lat: it.lat, lng: it.lng,
        address: it.address, rowIndex: it.row, async: true });
      if (res.code === 202 || (res.body && res.body.dispatched)) {
        it.state = 'fired'; fired += 1;
        sheet.getRange(it.row, PLANE_COL_V2_STATUS).setValue('rendering images...');
      } else {
        it.state = 'error';
        sheet.getRange(it.row, PLANE_COL_V2_STATUS).setValue(
          'render DISPATCH FAILED: ' + ((res.body && res.body.reason) || res.code));
      }
    } else if (it.state === 'fired') {
      const p = callV2_('/render', { taxlot: it.taxlot, probe: true });
      it.polls += 1;
      if (p.body && p.body.complete && p.body.images &&
          (p.body.nadir_bounds || it.polls >= 3)) {
        Object.keys(V2_IMG_COLS).forEach(function (v) {
          if (p.body.images[v]) sheet.getRange(it.row, V2_IMG_COLS[v]).setValue(p.body.images[v]);
        });
        if (p.body.nadir_bounds) {
          sheet.getRange(it.row, PLANE_COL_NADIR_BOUNDS)
               .setValue(JSON.stringify(p.body.nadir_bounds));
        }
        sheet.getRange(it.row, PLANE_COL_V2_STATUS)
             .setValue('images done (' + (p.body.capture_3d || '') + ')');
        it.state = 'done';
      } else if (p.body && p.body.note && p.body.note.indexOf('no cached 3D model') !== -1) {
        sheet.getRange(it.row, PLANE_COL_V2_STATUS)
             .setValue('NEEDS 3D MODEL — run Generate 3D Models (v2)');
        it.state = 'error';
      } else if (it.polls >= V2_MAX_POLLS) {
        sheet.getRange(it.row, PLANE_COL_V2_STATUS)
             .setValue('render TIMED OUT — check CloudWatch (plane-parcel-render)');
        it.state = 'error';
      }
    }
  });

  const open = job.items.filter(function (it) {
    return it.state === 'pending' || it.state === 'fired'; }).length;
  if (open === 0) {
    propsSvc.deleteProperty('planeImgJobV2');
    clearV2Trigger_('imagesTickV2_');
    const done = job.items.filter(function (it) { return it.state === 'done'; }).length;
    SpreadsheetApp.getActiveSpreadsheet().toast(
      'Images: finished — ' + done + '/' + job.items.length + ' rendered. ' +
      '(Re-renders can serve stale via CDN for up to the cache TTL.)');
  } else {
    propsSvc.setProperty('planeImgJobV2', JSON.stringify(job));
  }
}

// ============================================================
// PLANE PIPELINE v2 — STAGE C: BEDROCK DESCRIPTIONS
// ============================================================
// One Bedrock call per property with all five images. Writes a
// description per view (T/U/V/W), Responder Considerations (X),
// Information Needing Clarification (Y), and section-split nadir
// pins: element ids to Nadir Elements (P), concern ids to Nadir
// Concerns (S). ALL rows — residential and commercial — now use
// the FR Residential pin catalog (commercial placeholder per
// design lock). A row is "ready" when all five image URLs exist
// and the Alpha Description is empty (or a previous ERROR) or
// Nadir Elements is empty. Once descriptions land, "Sync Plane"
// pushes the row to GitHub and the viewer.

// Fetch the FR Residential pin catalog (cached 6 h). Returns
//   { pinCount, names, namesList, elementNames, elementIds,
//     concernNames, concernIds }
// where:
//   names        — full numbered "id. Name" list (all pins; kept for
//                  Pass 2 / any full-catalog use).
//   namesList    — [{id, name}] for every pin; used by currentPinsAsText_
//                  to resolve pin names for the Pass 1 rerun prompt.
//   elementNames — numbered "id. Name" list for ELEMENT-section pins
//                  only (ids in PIN_ELEMENT_RANGES), for the Pass 1
//                  prompt vocabulary.
//   elementIds   — { id: true } lookup of every element-section id,
//                  for Pass 1 validation.
//   concernNames — numbered "id. Name" list for CONCERN-section pins
//                  only (ids in PIN_CONCERN_RANGES), for the Pass 2
//                  prompt vocabulary.
//   concernIds   — { id: true } lookup of every concern-section id,
//                  for Pass 2 validation.
// Both subsets are DERIVED at runtime from the single catalog by id
// range — no second JSON file. Ids are contiguous 1..pinCount, so
// full-catalog validation stays a range check.
// v5.24: reads the merged, tagged pins-catalog.json and returns everything
// needed for BOTH passes for a given account type, in one cached object:
//   pinCount     — total pins in the catalog
//   namesList    — [{id,name}] for pins available to this account type
//                  (used by currentPinsAsText_ for the Pass 1 rerun)
//   elementNames — numbered "id. Name" list, role=primary + account_type match
//   elementIds   — { id: true } lookup for Pass 1 validation
//   frConcernNames / frConcernIds — role=concern, analysis ∋ 'fr', type match
//   wfConcernNames / wfConcernIds — role=concern, analysis ∋ 'wf', type match
// Filtering is by the per-pin tags (role / analysis / account_type) — no id
// ranges. Cached 6 h under a per-account-type key (pinCatalogV5:<type>).
function fetchPinCatalog_(accountType) {
  const type = normalizeAccountType(accountType); // 'residential' | 'commercial'
  const cacheKey = 'pinCatalogV5:' + type;
  const cache = CacheService.getScriptCache();
  const cached = cache.get(cacheKey);
  if (cached) return JSON.parse(cached);

  const res = UrlFetchApp.fetch(PIN_CATALOG_URL, { muteHttpExceptions: true });
  if (res.getResponseCode() !== 200) {
    throw new Error('Pin catalog fetch failed (HTTP ' + res.getResponseCode() + ')');
  }
  const cat = JSON.parse(res.getContentText());

  const forType = (cat.pins || []).filter(function (p) {
    return Array.isArray(p.account_type) && p.account_type.indexOf(type) !== -1;
  });
  const numbered = function (arr) { return arr.map(function (p) { return p.id + '. ' + p.name; }).join('\n'); };
  const idSet    = function (arr) { const o = {}; arr.forEach(function (p) { o[p.id] = true; }); return o; };
  const hasAnalysis = function (p, a) { return Array.isArray(p.analysis) && p.analysis.indexOf(a) !== -1; };

  const elementPins = forType.filter(function (p) { return p.role === 'primary'; });
  const frConcern   = forType.filter(function (p) { return p.role === 'concern' && hasAnalysis(p, 'fr'); });
  const wfConcern   = forType.filter(function (p) { return p.role === 'concern' && hasAnalysis(p, 'wf'); });

  const out = {
    pinCount:       cat.pin_count,
    namesList:      forType.map(function (p) { return { id: p.id, name: p.name }; }),
    elementNames:   numbered(elementPins),
    elementIds:     idSet(elementPins),
    frConcernNames: numbered(frConcern),
    frConcernIds:   idSet(frConcern),
    wfConcernNames: numbered(wfConcern),
    wfConcernIds:   idSet(wfConcern)
  };
  cache.put(cacheKey, JSON.stringify(out), 21600);
  return out;
}

// (v5.24: validatePlanePins_ removed — the generic full-catalog range
// validator had no callers. Pass 1 uses validateElementPins_ and Pass 2 uses
// validateConcernPins_, both gated to tagged id sets from fetchPinCatalog_.)

// Pass 1 validator: element-section ids only. Percentages of the nadir
// frame; values may sit outside 0–100 when a reviewer pinned on the
// basemap beyond the crop (v6.8.10). Never silently clamp to 5–95.
// Deduped, capped at PLANE_MAX_PINS.
function validateElementPins_(pins, elementIds) {
  if (!Array.isArray(pins)) return [];
  const out = [];
  const seen = {};
  for (let i = 0; i < pins.length && out.length < PLANE_MAX_PINS; i++) {
    const p = pins[i] || {};
    const x = parseFloat(p.x), y = parseFloat(p.y);
    if (isNaN(x) || isNaN(y)) continue;
    const id = parseInt(p.id, 10);
    if (isNaN(id) || !elementIds[id] || seen[id]) continue;
    seen[id] = true;
    const c = clampCoords(x, y);
    out.push({ id: id, x: c.x, y: c.y });
  }
  return out;
}

// Pass 2 validator: identical to validateElementPins_ but the id must be
// a CONCERN-section id (present in catalog.concernIds). Any id outside the
// concern sections — including an element-section id the model proposed
// despite the concern-only prompt — is dropped. Deduped, refused if
// outside the 5–95 box (never clamped), capped at PLANE_MAX_PINS.
// Guarantees element ids can never leak into Nadir Concerns (S).
function validateConcernPins_(pins, concernIds) {
  if (!Array.isArray(pins)) return [];
  const out = [];
  const seen = {};
  for (let i = 0; i < pins.length && out.length < PLANE_MAX_PINS; i++) {
    const p = pins[i] || {};
    const x = parseFloat(p.x), y = parseFloat(p.y);
    if (isNaN(x) || isNaN(y)) continue;
    if (x < 5 || x > 95 || y < 5 || y > 95) continue;
    const id = parseInt(p.id, 10);
    if (isNaN(id) || !concernIds[id] || seen[id]) continue;
    seen[id] = true;
    out.push({ id: id, x: x, y: y });
  }
  return out;
}

// (v5.24: splitPlanePinsBySection_ removed — it relied on the retired
// PIN_CONCERN_RANGES and had no callers. Pins are now split by catalog role
// tags at read time, not by id range.)

function guessImageMediaType_(url) {
  return /\.jpe?g($|\?)/i.test(String(url || '')) ? 'image/jpeg' : 'image/png';
}

// Pass 1 readiness: all five image URLs present AND Nadir Elements (P)
// still empty. (Pass 1 no longer touches the oblique descriptions —
// those are Pass 2 / Stage 4.) Regeneration of an already-pinned row
// goes through the This-Row menu item, which confirms first.
function planeRowReadyForElementPins_(rowVals) {
  const urlCols = [PLANE_COL_NADIR_URL, PLANE_COL_ALPHA_URL, PLANE_COL_BRAVO_URL,
                   PLANE_COL_CHARLIE_URL, PLANE_COL_DELTA_URL];
  for (let i = 0; i < urlCols.length; i++) {
    if (!String(rowVals[urlCols[i] - 1] || '').trim()) return false;
  }
  const elements = String(rowVals[PLANE_COL_ELEMENTS - 1] || '').trim();
  return !elements || elements.indexOf('ERROR:') === 0;
}

// Pass 2 readiness: Elements Reviewed (Q) === true AND the Alpha
// Description (T) is still empty or a previous ERROR. Q ALONE gates Pass 2
// (R, the Nadir Fixes note, is irrelevant here). A row that has been
// reviewed but not yet described is ready; once T is populated with a real
// description the row is done and won't be re-selected. Regeneration of an
// already-described row goes through the This-Row menu item, which
// confirms first.
function planeRowReadyForPass2_(rowVals) {
  if (rowVals[PLANE_COL_REVIEWED - 1] !== true) return false;
  const alpha = String(rowVals[PLANE_COL_ALPHA_DESC - 1] || '').trim();
  return !alpha || alpha.indexOf('ERROR:') === 0;
}

// Strips markdown fences if present, isolates the outermost JSON
// object, parses, and validates all required keys.
function parsePlaneDescriptions_(text) {
  if (!text) return null;
  let t = String(text).replace(/```json/gi, '').replace(/```/g, '').trim();
  const start = t.indexOf('{');
  const end   = t.lastIndexOf('}');
  if (start === -1 || end === -1 || end <= start) return null;
  t = t.substring(start, end + 1);
  let parsed;
  try { parsed = JSON.parse(t); } catch (e) {
    Logger.log('parsePlaneDescriptions_: JSON.parse failed — ' + e.message);
    return null;
  }
  const keys = ['alpha', 'bravo', 'charlie', 'delta', 'considerations', 'clarifications'];
  for (let i = 0; i < keys.length; i++) {
    if (typeof parsed[keys[i]] !== 'string' || !parsed[keys[i]].trim()) {
      Logger.log('parsePlaneDescriptions_: missing/empty key "' + keys[i] + '"');
      return null;
    }
  }
  if (!Array.isArray(parsed.nadir_pins)) {
    Logger.log('parsePlaneDescriptions_: nadir_pins missing or not an array');
    return null;
  }
  return parsed;
}

// Pass 1 parser: the element-pins response carries ONLY nadir_pins.
// Strips fences, isolates the outermost JSON object, requires
// nadir_pins to be an array. Returns the parsed object or null.
function parseElementPins_(text) {
  if (!text) return null;
  let t = String(text).replace(/```json/gi, '').replace(/```/g, '').trim();
  const start = t.indexOf('{');
  const end   = t.lastIndexOf('}');
  if (start === -1 || end === -1 || end <= start) return null;
  t = t.substring(start, end + 1);
  let parsed;
  try { parsed = JSON.parse(t); } catch (e) {
    Logger.log('parseElementPins_: JSON.parse failed — ' + e.message);
    return null;
  }
  if (!Array.isArray(parsed.nadir_pins)) {
    Logger.log('parseElementPins_: nadir_pins missing or not an array');
    return null;
  }
  return parsed;
}

function generateElementPinsV2() {
  const sheet = SpreadsheetApp.getActiveSpreadsheet().getSheetByName(PLANE_SHEET);
  if (!sheet) { SpreadsheetApp.getUi().alert('Sheet "' + PLANE_SHEET + '" not found'); return; }
  ensureV2Headers_(sheet);

  const lastRow = sheet.getLastRow();
  if (lastRow < 2) { SpreadsheetApp.getUi().alert('Plane sheet is empty.'); return; }
  const width = Math.max(sheet.getLastColumn(), PLANE_COL_V2_STATUS);
  const data  = sheet.getRange(2, 1, lastRow - 1, width).getValues();

  const readyRows = [];
  data.forEach(function (r, i) {
    const address = String(r[PLANE_COL_ADDRESS - 1] || '').trim();
    if (address && planeRowReadyForElementPins_(r)) readyRows.push(i + 2);
  });
  if (!readyRows.length) {
    SpreadsheetApp.getUi().alert('Plane Element Pins (Pass 1)',
      'No rows ready.\n(A row is ready when all five image URLs are present and Nadir Elements is empty.)',
      SpreadsheetApp.getUi().ButtonSet.OK);
    return;
  }

  let done = 0, failed = 0, attempted = 0;
  for (let i = 0; i < readyRows.length; i++) {
    if (attempted >= PLANE_DESC_BATCH) break;
    attempted++;
    try {
      if (processElementPinsRow_(sheet, readyRows[i])) done++;
      else failed++;
    } catch (e) {
      failed++;
      Logger.log('Element pins ERROR on row ' + readyRows[i] + ': ' + e.message);
      sheet.getRange(readyRows[i], PLANE_COL_V2_STATUS)
           .setValue('element pins FAILED: ' + e.message.substring(0, 80));
    }
    Utilities.sleep(2000);
  }

  const remaining = readyRows.length - attempted + failed;
  SpreadsheetApp.getUi().alert('Plane Element Pins (Pass 1)',
    'Completed: ' + done + '\nFailed: ' + failed +
    (remaining > 0 ? '\nRemaining: ' + remaining + ' — run again to continue.' : '\nAll ready rows processed.') +
    (done > 0 ? '\n\nReview the element pins on the nadir image. Tick "Elements Reviewed" when correct, or write a note in "Nadir Fixes" to rerun. Pass 2 (concerns + descriptions) runs after review.' : ''),
    SpreadsheetApp.getUi().ButtonSet.OK);
}

function generateElementPinsForActiveRow() {
  const ss = SpreadsheetApp.getActiveSpreadsheet();
  const sheet = ss.getSheetByName(PLANE_SHEET);
  if (!sheet) { SpreadsheetApp.getUi().alert('Sheet "' + PLANE_SHEET + '" not found'); return; }
  if (ss.getActiveSheet().getName() !== PLANE_SHEET) {
    SpreadsheetApp.getUi().alert('Please select a row on the "' + PLANE_SHEET + '" sheet.');
    return;
  }
  const row = sheet.getActiveCell().getRow();
  if (row < 2) { SpreadsheetApp.getUi().alert('Please select a data row.'); return; }

  const address = String(sheet.getRange(row, PLANE_COL_ADDRESS).getValue() || '').trim();
  if (!address) { SpreadsheetApp.getUi().alert('Row ' + row + ' has no Property Address.'); return; }

  const existing = String(sheet.getRange(row, PLANE_COL_ELEMENTS).getValue() || '').trim();
  if (existing && existing.indexOf('ERROR:') !== 0) {
    const ui = SpreadsheetApp.getUi();
    const answer = ui.alert('Regenerate?',
      'Row ' + row + ' already has element pins.\nRegenerate element pins for:\n' + address +
      '?\n\n(This also clears the Elements Reviewed checkbox.)',
      ui.ButtonSet.YES_NO);
    if (answer !== ui.Button.YES) return;
  }

  const ok = processElementPinsRow_(sheet, row);
  SpreadsheetApp.getUi().alert('Plane Element Pins (Pass 1)',
    ok ? 'Element pins written for:\n' + address + '\n\nReview them on the nadir image, then tick "Elements Reviewed" (or write a "Nadir Fixes" note to rerun).'
       : 'Element pin generation FAILED for:\n' + address + '\nSee the v2 Status column and execution logs.',
    SpreadsheetApp.getUi().ButtonSet.OK);
}

// Build the element-review URL for a Plane row: the review page reads
// the nadir image URL and the element-pins JSON from its query string
// and renders numbered markers on the real nadir with a named legend
// strip. Names are resolved page-side from the live catalog; x,y are
// percentages on the image, so no bounds are needed. Returns the URL
// string, or null if the row lacks a nadir URL or element pins.
function buildElementReviewUrl_(sheet, row) {
  const nadirUrl = String(sheet.getRange(row, PLANE_COL_NADIR_URL).getValue() || '').trim();
  const pinsRaw  = String(sheet.getRange(row, PLANE_COL_ELEMENTS).getValue() || '').trim();
  const address  = String(sheet.getRange(row, PLANE_COL_ADDRESS).getValue() || '').trim();
  const siteNo   = String(sheet.getRange(row, PLANE_COL_SITE_NO).getValue() || '').trim();
  if (!nadirUrl || !pinsRaw) return null;
  // Validate the pins cell is JSON we can hand off (don't ship an ERROR token).
  let pins;
  try { pins = JSON.parse(pinsRaw); } catch (e) { return null; }
  if (!Array.isArray(pins)) return null;
  return withReviewSiteNo_(
    ELEMENT_REVIEW_URL +
      '?nadir=' + encodeURIComponent(nadirUrl) +
      '&pins='  + encodeURIComponent(JSON.stringify(pins)) +
      (address ? '&addr=' + encodeURIComponent(address) : ''),
    siteNo);
}

// Menu action: open the element-review page for the active Plane row.
// Shows a clickable link in a dialog (Apps Script can't open a tab
// directly). One row at a time — matches the review workflow, adds no
// column. Use after Pass 1 to eyeball pins before ticking Elements
// Reviewed.
function openElementReviewForActiveRow() {
  const ss = SpreadsheetApp.getActiveSpreadsheet();
  const sheet = ss.getSheetByName(PLANE_SHEET);
  if (!sheet) { SpreadsheetApp.getUi().alert('Sheet "' + PLANE_SHEET + '" not found'); return; }
  if (ss.getActiveSheet().getName() !== PLANE_SHEET) {
    SpreadsheetApp.getUi().alert('Please select a row on the "' + PLANE_SHEET + '" sheet.');
    return;
  }
  const row = sheet.getActiveCell().getRow();
  if (row < 2) { SpreadsheetApp.getUi().alert('Please select a data row.'); return; }

  const url = buildElementReviewUrl_(sheet, row);
  if (!url) {
    SpreadsheetApp.getUi().alert('Element Review',
      'Row ' + row + ' has no nadir image or no element pins yet.\nRun "Generate Element Pins — Pass 1 (This Row)" first.',
      SpreadsheetApp.getUi().ButtonSet.OK);
    return;
  }
  const address = String(sheet.getRange(row, PLANE_COL_ADDRESS).getValue() || '').trim();
  reviewOpenDialog_(address, url);
}
// Render the current element pins as human-readable lines for the rerun
// prompt: one "<id> = <name> at (x, y)" line per pin, names resolved from
// catalog.namesList. `pinsRaw` is the raw Nadir Elements (P) cell value (a
// JSON array string). Returns '' when there are no current pins, when the
// cell is not valid pin JSON, or when the array is empty. Unknown ids fall
// back to "id <n>".
function currentPinsAsText_(pinsRaw, catalog) {
  let pins;
  try { pins = JSON.parse(pinsRaw); } catch (e) { return ''; }
  if (!Array.isArray(pins) || !pins.length) return '';
  const nameById = {};
  ((catalog && catalog.namesList) || []).forEach(function (n) { nameById[n.id] = n.name; });
  const lines = [];
  pins.forEach(function (p) {
    if (!p) return;
    const id = parseInt(p.id, 10);
    if (isNaN(id)) return;
    const name = nameById[id] || ('id ' + id);
    const x = (typeof p.x === 'number') ? p.x : parseFloat(p.x);
    const y = (typeof p.y === 'number') ? p.y : parseFloat(p.y);
    lines.push(id + ' = ' + name + ' at (' + x + ', ' + y + ')');
  });
  return lines.join('\n');
}

// Shared core for Pass 1 AND the rerun. Builds the element-pins system
// prompt (planeElementPinsPrompt_ + the ELEMENT vocabulary + KB context
// from kbQuery), fetches the five images, sends ONE Bedrock call whose
// trailing user text is `trailingInstruction`, parses + validates
// element-section pins, writes them to Nadir Elements (P), and resets
// Elements Reviewed (Q) to unchecked (fresh pins = not yet reviewed).
// Writes NOTHING to Nadir Fixes (R) or to S:Y. `statusVerb` seeds the
// in-progress status ("<statusVerb>..."). Returns true on success (pins
// written, or a legitimately empty pin set), false on any failure.
function runElementPinsCall_(sheet, row, trailingInstruction, statusVerb, kbQuery) {
  const address     = String(sheet.getRange(row, PLANE_COL_ADDRESS).getValue() || '').trim();
  const accountType = normalizeAccountType(sheet.getRange(row, PLANE_COL_ACCOUNT_TYPE).getValue());

  const viewDefs = [
    { key: 'nadir',   urlCol: PLANE_COL_NADIR_URL,   label: 'IMAGE 1 — NADIR (straight-down orthophoto view — place pins on this image)' },
    { key: 'alpha',   urlCol: PLANE_COL_ALPHA_URL,   label: 'IMAGE 2 — ALPHA (oblique, FRONT of the property)' },
    { key: 'bravo',   urlCol: PLANE_COL_BRAVO_URL,   label: 'IMAGE 3 — BRAVO (oblique, RIGHT side of the property)' },
    { key: 'charlie', urlCol: PLANE_COL_CHARLIE_URL, label: 'IMAGE 4 — CHARLIE (oblique, REAR of the property)' },
    { key: 'delta',   urlCol: PLANE_COL_DELTA_URL,   label: 'IMAGE 5 — DELTA (oblique, LEFT side of the property)' }
  ];

  const catalog = fetchPinCatalog_(accountType);
  const prompt = planeElementPinsPrompt_() +
    '\n\nAPPROVED ELEMENT PIN VOCABULARY (use ONLY these ids):\n' +
    catalog.elementNames;
  const kbContext  = queryKnowledgeBase(kbQuery);
  const fullPrompt = kbContext ? prompt + '\n\nREFERENCE CONTEXT FROM KNOWLEDGE BASE:\n' + kbContext : prompt;

  sheet.getRange(row, PLANE_COL_V2_STATUS).setValue(statusVerb + '...');
  SpreadsheetApp.flush();

  const userContent = [];
  for (let i = 0; i < viewDefs.length; i++) {
    const v   = viewDefs[i];
    const url = String(sheet.getRange(row, v.urlCol).getValue() || '').trim();
    if (!url) {
      sheet.getRange(row, PLANE_COL_V2_STATUS).setValue('element pins FAILED: missing ' + v.key + ' image URL');
      return false;
    }
    const b64 = fetchImageAsBase64(url);
    if (!b64) {
      sheet.getRange(row, PLANE_COL_V2_STATUS).setValue('element pins FAILED: image fetch (' + v.key + ')');
      return false;
    }
    userContent.push({ type: 'text', text: v.label });
    userContent.push({ type: 'image', source: { type: 'base64', media_type: guessImageMediaType_(url), data: b64 } });
  }
  userContent.push({ type: 'text', text: trailingInstruction });

  const result = callBedrock(fullPrompt, userContent, 1000);
  if (!result) {
    sheet.getRange(row, PLANE_COL_V2_STATUS).setValue('element pins FAILED: Bedrock call — see logs');
    return false;
  }
  const parsed = parseElementPins_(result);
  if (!parsed) {
    Logger.log('Element pins raw response (row ' + row + '): ' + result.substring(0, 500));
    sheet.getRange(row, PLANE_COL_V2_STATUS).setValue('element pins FAILED: JSON parse — see logs');
    return false;
  }

  const pins = validateElementPins_(parsed.nadir_pins, catalog.elementIds);
  writePlainCell(sheet, row, PLANE_COL_ELEMENTS, pins.length ? JSON.stringify(pins) : '');
  // Fresh element pins invalidate any prior human review.
  sheet.getRange(row, PLANE_COL_REVIEWED).setValue(false);
  sheet.getRange(row, PLANE_COL_V2_STATUS)
       .setValue('element pins done [' + accountType + ', ' + pins.length + ' elements] — awaiting review');
  SpreadsheetApp.flush();
  Logger.log('Element pins written: row ' + row + ' — ' + address +
             ' [' + accountType + ', ' + pins.length + ' elements]');
  return pins.length > 0 || parsed.nadir_pins.length === 0;
}

// Pass 1 per-row processor: a thin wrapper over runElementPinsCall_ with
// the Pass 1 trailing instruction (address + account type + "identify the
// physical property elements"). Element pins land in P and Q is reset;
// nothing is written to R or S:Y (concerns/descriptions are Pass 2 /
// Stage 4). Returns true on success.
function processElementPinsRow_(sheet, row) {
  const address     = String(sheet.getRange(row, PLANE_COL_ADDRESS).getValue() || '').trim();
  const accountType = normalizeAccountType(sheet.getRange(row, PLANE_COL_ACCOUNT_TYPE).getValue());
  const trailingInstruction =
    'Property address: ' + address + ' [' + accountType + ']. ' +
    'Identify the physical property elements and return ONLY the JSON object described in your instructions.';
  return runElementPinsCall_(sheet, row, trailingInstruction,
    'generating element pins',
    'aerial property intelligence property elements structures access');
}

// ── PASS 1 RERUN — RE-PIN FROM ANALYST FIXES (v5.22) ────────
// Re-pins a row's ELEMENT pins using the analyst's Nadir Fixes (R) note as
// authoritative corrections (Option C — text coordinates, no render
// Lambda). The rerun sends the SAME five clean images as Pass 1, plus the
// current pins as named text and the R note, and asks the model to keep
// correct pins, fix wrong ones, add missing ones, and drop bad ones. It
// rewrites P and resets Q (fresh pins = unreviewed). It NEVER writes R — R
// is the analyst's standing record; overwrite it by hand to steer a
// subsequent rerun. R has no bearing on Pass 2; Q ALONE gates it.

// Per-row rerun processor. Reads the R note (returns the 'no-fixes' token
// when R is empty, so callers can message precisely) and the current P
// pins, builds the named-pin text, builds the rerun trailing instruction,
// and runs the shared element-pins call with statusVerb 'rerunning element
// pins'. Never touches R. Returns 'no-fixes' | true | false.
function rerunElementPinsRow_(sheet, row) {
  const address     = String(sheet.getRange(row, PLANE_COL_ADDRESS).getValue() || '').trim();
  const accountType = normalizeAccountType(sheet.getRange(row, PLANE_COL_ACCOUNT_TYPE).getValue());
  const fixesNote   = String(sheet.getRange(row, PLANE_COL_FIXES).getValue() || '').trim();
  if (!fixesNote) return 'no-fixes';

  const pinsRaw = String(sheet.getRange(row, PLANE_COL_ELEMENTS).getValue() || '').trim();
  const catalog = fetchPinCatalog_(accountType);
  const currentPinsText = currentPinsAsText_(pinsRaw, catalog);

  const trailingInstruction =
    planeElementRerunInstruction_(address, accountType, currentPinsText, fixesNote);
  return runElementPinsCall_(sheet, row, trailingInstruction,
    'rerunning element pins',
    'aerial property intelligence property elements structures access');
}

// This-Row rerun. Ignores the Elements Reviewed checkbox (the analyst
// explicitly picked this row) but still REQUIRES a non-empty Nadir Fixes
// note — alerts if R is empty. R is left untouched (kept for the record).
function rerunElementPinsForActiveRow() {
  const ss = SpreadsheetApp.getActiveSpreadsheet();
  const sheet = ss.getSheetByName(PLANE_SHEET);
  if (!sheet) { SpreadsheetApp.getUi().alert('Sheet "' + PLANE_SHEET + '" not found'); return; }
  if (ss.getActiveSheet().getName() !== PLANE_SHEET) {
    SpreadsheetApp.getUi().alert('Please select a row on the "' + PLANE_SHEET + '" sheet.');
    return;
  }
  const row = sheet.getActiveCell().getRow();
  if (row < 2) { SpreadsheetApp.getUi().alert('Please select a data row.'); return; }

  const address = String(sheet.getRange(row, PLANE_COL_ADDRESS).getValue() || '').trim();
  if (!address) { SpreadsheetApp.getUi().alert('Row ' + row + ' has no Property Address.'); return; }

  const fixesNote = String(sheet.getRange(row, PLANE_COL_FIXES).getValue() || '').trim();
  if (!fixesNote) {
    SpreadsheetApp.getUi().alert('Rerun Element Pins',
      'Row ' + row + ' has no "Nadir Fixes" note.\nWrite the correction you want applied in column R, then rerun.',
      SpreadsheetApp.getUi().ButtonSet.OK);
    return;
  }

  const outcome = rerunElementPinsRow_(sheet, row);
  SpreadsheetApp.getUi().alert('Rerun Element Pins (Pass 1)',
    outcome === true
      ? 'Element pins re-generated from your Nadir Fixes note for:\n' + address +
        '\n\nYour "Nadir Fixes" note is kept for the record (not cleared). Review the new pins, then tick "Elements Reviewed" — or edit the note and rerun again.'
      : 'Rerun FAILED for:\n' + address + '\nSee the v2 Status column and execution logs.\n\nYour "Nadir Fixes" note was left untouched.',
    SpreadsheetApp.getUi().ButtonSet.OK);
}

// Batch rerun. Selects every row where Nadir Fixes (R) is non-empty AND
// Elements Reviewed (Q) is unchecked, processes up to PLANE_DESC_BATCH per
// run (2 s between rows), and NEVER touches R. Reports completed / failed /
// remaining.
function rerunElementPinsBatch() {
  const sheet = SpreadsheetApp.getActiveSpreadsheet().getSheetByName(PLANE_SHEET);
  if (!sheet) { SpreadsheetApp.getUi().alert('Sheet "' + PLANE_SHEET + '" not found'); return; }
  ensureV2Headers_(sheet);

  const lastRow = sheet.getLastRow();
  if (lastRow < 2) { SpreadsheetApp.getUi().alert('Plane sheet is empty.'); return; }
  const width = Math.max(sheet.getLastColumn(), PLANE_COL_V2_STATUS);
  const data  = sheet.getRange(2, 1, lastRow - 1, width).getValues();

  const flagged = [];
  data.forEach(function (r, i) {
    const address = String(r[PLANE_COL_ADDRESS - 1] || '').trim();
    if (!address) return;
    const fixesNote = String(r[PLANE_COL_FIXES - 1] || '').trim();
    const reviewed  = r[PLANE_COL_REVIEWED - 1] === true;
    if (fixesNote && !reviewed) flagged.push(i + 2);
  });
  if (!flagged.length) {
    SpreadsheetApp.getUi().alert('Rerun Element Pins (All Flagged)',
      'No flagged rows.\n(A row is flagged for rerun when it has a "Nadir Fixes" note AND "Elements Reviewed" is unchecked.)',
      SpreadsheetApp.getUi().ButtonSet.OK);
    return;
  }

  let done = 0, failed = 0, attempted = 0;
  for (let i = 0; i < flagged.length; i++) {
    if (attempted >= PLANE_DESC_BATCH) break;
    attempted++;
    try {
      if (rerunElementPinsRow_(sheet, flagged[i]) === true) done++;
      else failed++;
    } catch (e) {
      failed++;
      Logger.log('Rerun element pins ERROR on row ' + flagged[i] + ': ' + e.message);
      sheet.getRange(flagged[i], PLANE_COL_V2_STATUS)
           .setValue('rerun FAILED: ' + e.message.substring(0, 80));
    }
    Utilities.sleep(2000);
  }

  const remaining = flagged.length - attempted + failed;
  SpreadsheetApp.getUi().alert('Rerun Element Pins (All Flagged)',
    'Completed: ' + done + '\nFailed: ' + failed +
    (remaining > 0 ? '\nRemaining: ' + remaining + ' — run again to continue.' : '\nAll flagged rows processed.') +
    '\n\n"Nadir Fixes" notes are kept for the record (never cleared). Review the new pins and tick "Elements Reviewed" when correct.',
    SpreadsheetApp.getUi().ButtonSet.OK);
}

// ============================================================
// PLANE PIPELINE v2 — PASS 2: CONCERNS + DESCRIPTIONS (v5.23)
// ============================================================
// Runs ONLY on rows a human has reviewed (Elements Reviewed / Q ticked).
// One Bedrock call over the same five images, with the approved element
// pins supplied as trusted ground truth (named text). Produces the
// evaluative layer and writes it to the row:
//   S  Nadir Concerns      — concern pins JSON (concern-section ids only)
//   T  Alpha Description
//   U  Bravo Description
//   V  Charlie Description
//   W  Delta Description
//   X  Responder Considerations
//   Y  Information Needing Clarification
// Pass 2 NEVER writes P (element pins), Q (reviewed), or R (fixes) — the
// approved element pins are frozen. Once T is populated, the row is
// Sync-complete and processPlaneSheet will publish it.

// Shared core: build the Pass 2 system prompt (planeConcernAndDescPrompt_
// + the CONCERN vocabulary + KB context), fetch the five images, send ONE
// Bedrock call whose trailing user text carries the address plus the
// approved element pins as named "id = name at (x, y)" text, parse with
// parsePlaneDescriptions_, validate nadir_pins as concern pins, and write
// S,T,U,V,W,X,Y. Returns true on success (descriptions written), false on
// any failure. Writes nothing to P/Q/R.
function runPass2Call_(sheet, row) {
  const address     = String(sheet.getRange(row, PLANE_COL_ADDRESS).getValue() || '').trim();
  const accountType = normalizeAccountType(sheet.getRange(row, PLANE_COL_ACCOUNT_TYPE).getValue());

  const viewDefs = [
    { key: 'nadir',   urlCol: PLANE_COL_NADIR_URL,   label: 'IMAGE 1 — NADIR (straight-down orthophoto view — place concern pins on this image)' },
    { key: 'alpha',   urlCol: PLANE_COL_ALPHA_URL,   label: 'IMAGE 2 — ALPHA (oblique, FRONT of the property)' },
    { key: 'bravo',   urlCol: PLANE_COL_BRAVO_URL,   label: 'IMAGE 3 — BRAVO (oblique, RIGHT side of the property)' },
    { key: 'charlie', urlCol: PLANE_COL_CHARLIE_URL, label: 'IMAGE 4 — CHARLIE (oblique, REAR of the property)' },
    { key: 'delta',   urlCol: PLANE_COL_DELTA_URL,   label: 'IMAGE 5 — DELTA (oblique, LEFT side of the property)' }
  ];

  const catalog = fetchPinCatalog_(accountType);
  const prompt = planeConcernAndDescPrompt_() +
    '\n\nAPPROVED CONCERN PIN VOCABULARY (use ONLY these ids):\n' +
    catalog.frConcernNames;
  const kbContext  = queryKnowledgeBase('first responder property access hazards egress visibility operational concerns');
  const fullPrompt = kbContext ? prompt + '\n\nREFERENCE CONTEXT FROM KNOWLEDGE BASE:\n' + kbContext : prompt;

  sheet.getRange(row, PLANE_COL_V2_STATUS).setValue('generating concerns + descriptions...');
  SpreadsheetApp.flush();

  const userContent = [];
  for (let i = 0; i < viewDefs.length; i++) {
    const v   = viewDefs[i];
    const url = String(sheet.getRange(row, v.urlCol).getValue() || '').trim();
    if (!url) {
      sheet.getRange(row, PLANE_COL_V2_STATUS).setValue('pass 2 FAILED: missing ' + v.key + ' image URL');
      return false;
    }
    const b64 = fetchImageAsBase64(url);
    if (!b64) {
      sheet.getRange(row, PLANE_COL_V2_STATUS).setValue('pass 2 FAILED: image fetch (' + v.key + ')');
      return false;
    }
    userContent.push({ type: 'text', text: v.label });
    userContent.push({ type: 'image', source: { type: 'base64', media_type: guessImageMediaType_(url), data: b64 } });
  }

  const pinsRaw = String(sheet.getRange(row, PLANE_COL_ELEMENTS).getValue() || '').trim();
  const confirmedText = currentPinsAsText_(pinsRaw, catalog);
  userContent.push({ type: 'text',
    text: 'Property address: ' + address + ' [' + accountType + '].\n\n' +
          'CONFIRMED PROPERTY ELEMENTS (human-approved ground truth), as "id = name at (x, y)" on the nadir:\n' +
          (confirmedText || '(no element pins were placed for this property)') +
          '\n\nUsing these confirmed elements and all five images, return ONLY the JSON object described in your instructions (concern pins in "nadir_pins", plus the four view descriptions, considerations, and clarifications).' });

  const result = callBedrock(fullPrompt, userContent, 4000);
  if (!result) {
    sheet.getRange(row, PLANE_COL_V2_STATUS).setValue('pass 2 FAILED: Bedrock call — see logs');
    return false;
  }
  const parsed = parsePlaneDescriptions_(result);
  if (!parsed) {
    Logger.log('Pass 2 raw response (row ' + row + '): ' + result.substring(0, 600));
    sheet.getRange(row, PLANE_COL_V2_STATUS).setValue('pass 2 FAILED: JSON parse — see logs');
    return false;
  }

  const concernPins = validateConcernPins_(parsed.nadir_pins, catalog.frConcernIds);
  // Write the evaluative layer. Concern pins (S) then the four descriptions
  // (T:W) then considerations (X) and clarifications (Y). No P/Q/R writes.
  writePlainCell(sheet, row, PLANE_COL_CONCERNS_P, concernPins.length ? JSON.stringify(concernPins) : '');
  writePlainCell(sheet, row, PLANE_COL_ALPHA_DESC,   parsed.alpha);
  writePlainCell(sheet, row, PLANE_COL_BRAVO_DESC,   parsed.bravo);
  writePlainCell(sheet, row, PLANE_COL_CHARLIE_DESC, parsed.charlie);
  writePlainCell(sheet, row, PLANE_COL_DELTA_DESC,   parsed.delta);
  writePlainCell(sheet, row, PLANE_COL_CONSIDER,     parsed.considerations);
  writePlainCell(sheet, row, PLANE_COL_CLARIFY,      parsed.clarifications);
  sheet.getRange(row, PLANE_COL_V2_STATUS)
       .setValue('pass 2 done [' + accountType + ', ' + concernPins.length + ' concerns] — ready to sync');
  SpreadsheetApp.flush();
  Logger.log('Pass 2 written: row ' + row + ' — ' + address +
             ' [' + accountType + ', ' + concernPins.length + ' concerns]');
  return true;
}

// Pass 2 per-row processor. Thin wrapper over runPass2Call_ (kept separate
// so the batch/active-row callers read symmetrically with Pass 1).
function processPass2Row_(sheet, row) {
  return runPass2Call_(sheet, row);
}

// Pass 2 batch: every row that is Pass-2-ready (Q === true AND Alpha
// Description empty/ERROR), up to PLANE_DESC_BATCH per run (2 s between
// rows). A timed-out or failed row leaves T empty, so it stays ready and
// is picked up on the next run automatically.
function generatePass2V2() {
  const sheet = SpreadsheetApp.getActiveSpreadsheet().getSheetByName(PLANE_SHEET);
  if (!sheet) { SpreadsheetApp.getUi().alert('Sheet "' + PLANE_SHEET + '" not found'); return; }
  ensureV2Headers_(sheet);

  const lastRow = sheet.getLastRow();
  if (lastRow < 2) { SpreadsheetApp.getUi().alert('Plane sheet is empty.'); return; }
  const width = Math.max(sheet.getLastColumn(), PLANE_COL_V2_STATUS);
  const data  = sheet.getRange(2, 1, lastRow - 1, width).getValues();

  const readyRows = [];
  data.forEach(function (r, i) {
    const address = String(r[PLANE_COL_ADDRESS - 1] || '').trim();
    if (address && planeRowReadyForPass2_(r)) readyRows.push(i + 2);
  });
  if (!readyRows.length) {
    SpreadsheetApp.getUi().alert('Plane Pass 2 (Concerns + Descriptions)',
      'No rows ready.\n(A row is ready when "Elements Reviewed" is ticked and the Alpha Description is still empty.)',
      SpreadsheetApp.getUi().ButtonSet.OK);
    return;
  }

  let done = 0, failed = 0, attempted = 0;
  for (let i = 0; i < readyRows.length; i++) {
    if (attempted >= PLANE_DESC_BATCH) break;
    attempted++;
    try {
      if (processPass2Row_(sheet, readyRows[i])) done++;
      else failed++;
    } catch (e) {
      failed++;
      Logger.log('Pass 2 ERROR on row ' + readyRows[i] + ': ' + e.message);
      sheet.getRange(readyRows[i], PLANE_COL_V2_STATUS)
           .setValue('pass 2 FAILED: ' + e.message.substring(0, 80));
    }
    Utilities.sleep(2000);
  }

  const remaining = readyRows.length - attempted + failed;
  SpreadsheetApp.getUi().alert('Plane Pass 2 (Concerns + Descriptions)',
    'Completed: ' + done + '\nFailed: ' + failed +
    (remaining > 0 ? '\nRemaining: ' + remaining + ' — run again to continue.' : '\nAll ready rows processed.') +
    (done > 0 ? '\n\nCompleted rows are ready to publish — run "Sync Plane".' : ''),
    SpreadsheetApp.getUi().ButtonSet.OK);
}

// Pass 2 for the active row. Ignores the readiness predicate's "T empty"
// clause (so you can regenerate a described row) but still REQUIRES the row
// to be reviewed — Q === true — and confirms before overwriting existing
// descriptions.
function generatePass2ForActiveRow() {
  const ss = SpreadsheetApp.getActiveSpreadsheet();
  const sheet = ss.getSheetByName(PLANE_SHEET);
  if (!sheet) { SpreadsheetApp.getUi().alert('Sheet "' + PLANE_SHEET + '" not found'); return; }
  if (ss.getActiveSheet().getName() !== PLANE_SHEET) {
    SpreadsheetApp.getUi().alert('Please select a row on the "' + PLANE_SHEET + '" sheet.');
    return;
  }
  const row = sheet.getActiveCell().getRow();
  if (row < 2) { SpreadsheetApp.getUi().alert('Please select a data row.'); return; }

  const address = String(sheet.getRange(row, PLANE_COL_ADDRESS).getValue() || '').trim();
  if (!address) { SpreadsheetApp.getUi().alert('Row ' + row + ' has no Property Address.'); return; }

  if (sheet.getRange(row, PLANE_COL_REVIEWED).getValue() !== true) {
    SpreadsheetApp.getUi().alert('Plane Pass 2',
      'Row ' + row + ' is not reviewed yet.\nTick "Elements Reviewed" once the element pins are correct, then run Pass 2.',
      SpreadsheetApp.getUi().ButtonSet.OK);
    return;
  }

  const existing = String(sheet.getRange(row, PLANE_COL_ALPHA_DESC).getValue() || '').trim();
  if (existing && existing.indexOf('ERROR:') !== 0) {
    const ui = SpreadsheetApp.getUi();
    const answer = ui.alert('Regenerate?',
      'Row ' + row + ' already has Pass 2 output.\nRegenerate concerns + descriptions for:\n' + address + '?',
      ui.ButtonSet.YES_NO);
    if (answer !== ui.Button.YES) return;
  }

  const ok = processPass2Row_(sheet, row);
  SpreadsheetApp.getUi().alert('Plane Pass 2 (Concerns + Descriptions)',
    ok ? 'Concerns + descriptions written for:\n' + address + '\n\nRow is ready to publish — run "Sync Plane".'
       : 'Pass 2 FAILED for:\n' + address + '\nSee the v2 Status column and execution logs.',
    SpreadsheetApp.getUi().ButtonSet.OK);
}

// One-shot: fill empty Nadir Bounds cells from existing nadir-meta.json
// via zero-side-effect probes. Safe to re-run anytime.
function backfillNadirBounds() {
  const sheet = SpreadsheetApp.getActiveSpreadsheet().getSheetByName(PLANE_SHEET);
  if (!sheet) { SpreadsheetApp.getUi().alert('Sheet "' + PLANE_SHEET + '" not found'); return; }
  const lastRow = sheet.getLastRow();
  let filled = 0, missing = 0;
  for (let row = 2; row <= lastRow; row++) {
    const taxlot = String(sheet.getRange(row, PLANE_COL_TAXLOT).getValue() || '').trim();
    if (!taxlot) continue;
    if (String(sheet.getRange(row, PLANE_COL_NADIR_BOUNDS).getValue() || '').trim()) continue;
    const p = callV2_('/render', { taxlot: taxlot, probe: true });
    if (p.body && p.body.nadir_bounds) {
      sheet.getRange(row, PLANE_COL_NADIR_BOUNDS)
           .setValue(JSON.stringify(p.body.nadir_bounds));
      filled++;
    } else {
      missing++;
      Logger.log('backfillNadirBounds: no meta yet for ' + taxlot + ' (row ' + row + ')');
    }
  }
  SpreadsheetApp.getUi().alert('Nadir Bounds Backfill',
    'Filled: ' + filled + '\nStill missing: ' + missing +
    (missing ? '\n(Missing rows: re-run after renders finish, or check logs.)' : ''),
    SpreadsheetApp.getUi().ButtonSet.OK);
}

// ============================================================
// PLANE SHEET — GITHUB SYNC
// ============================================================
// Dedicated processor for the NEW Plane sheet layout (the shared
// processSheet() keeps the v5.14 layout for Drone/Interior).
// Produces data/plane/{viewId}.json in the drone JSON schema plus
// lat/lng. The nadir block carries BOTH the split pin arrays
// (element_pins / concern_pins — consumed by viewer v2.7.0's
// color-coded overlay) and a merged pins array (consumed by the
// current viewer v2.6.0). Updates index.json views.plane and the
// HOA maps, writes the FR Link (Z) and Upload Date (H), and
// updates Intel Links.
// A row is complete when: all five image URLs, all four oblique
// descriptions, and Nadir Elements are present. Nadir Concerns may
// be empty (legacy commercial rows park their pins in Elements).
//
// v5.21 note: Pass 1 (element pins) writes only Nadir Elements; the
// four oblique descriptions come from Pass 2 (Stage 4, not yet built).
// So during the Pass 1→Pass 2 gap, element-only rows are intentionally
// INCOMPLETE here and Sync skips them — publish resumes once Pass 2
// fills T:W. This is expected, not a bug.

function processPlaneSheet() {
  const creds = getCredentials();
  const sheet = SpreadsheetApp.getActiveSpreadsheet().getSheetByName(PLANE_SHEET);
  if (!sheet) { Logger.log('Sheet not found: ' + PLANE_SHEET); return; }

  const data    = sheet.getDataRange().getValues();
  const hoaMap  = fetchHoaMap();
  const files   = [];
  const updates = [];
  let processed = 0, skipped = 0;

  for (let i = 1; i < data.length; i++) {
    const row = data[i];
    const accountType    = normalizeAccountType(row[PLANE_COL_ACCOUNT_TYPE - 1]);
    const accountName    = row[PLANE_COL_ACCOUNT - 1];
    const address        = row[PLANE_COL_ADDRESS - 1];
    const hoaTag         = row[PLANE_COL_HOA - 1];
    const nadirUrl       = row[PLANE_COL_NADIR_URL - 1];
    const elementsRaw    = row[PLANE_COL_ELEMENTS - 1];
    const concernsRaw    = row[PLANE_COL_CONCERNS_P - 1];
    const boundsRaw      = row[PLANE_COL_NADIR_BOUNDS - 1];
    const alphaUrl       = row[PLANE_COL_ALPHA_URL - 1];
    const alphaDesc      = row[PLANE_COL_ALPHA_DESC - 1];
    const bravoUrl       = row[PLANE_COL_BRAVO_URL - 1];
    const bravoDesc      = row[PLANE_COL_BRAVO_DESC - 1];
    const charlieUrl     = row[PLANE_COL_CHARLIE_URL - 1];
    const charlieDesc    = row[PLANE_COL_CHARLIE_DESC - 1];
    const deltaUrl       = row[PLANE_COL_DELTA_URL - 1];
    const deltaDesc      = row[PLANE_COL_DELTA_DESC - 1];
    const considerations = row[PLANE_COL_CONSIDER - 1];
    const clarifications = row[PLANE_COL_CLARIFY - 1];
    const viewer360      = row[PLANE_COL_VIEWER360 - 1];
    const lat            = parseFloat(row[PLANE_COL_LAT - 1]);
    const lng            = parseFloat(row[PLANE_COL_LNG - 1]);

    if (!accountName || !address) { skipped++; continue; }
    if (!nadirUrl || !elementsRaw || !alphaUrl || !alphaDesc ||
        !bravoUrl || !bravoDesc || !charlieUrl || !charlieDesc ||
        !deltaUrl || !deltaDesc) {
      Logger.log('Plane sync skipping (incomplete): ' + accountName);
      skipped++; continue;
    }
    if (String(alphaDesc).indexOf('ERROR:') === 0) {
      Logger.log('Plane sync skipping (errored descriptions): ' + accountName);
      skipped++; continue;
    }
    let elementPins = [], concernPins = [], bounds = null;
    try { elementPins = JSON.parse(elementsRaw) || []; } catch (e) {
      Logger.log('Plane sync skipping (bad Nadir Elements JSON): ' + accountName);
      skipped++; continue;
    }
    if (String(concernsRaw || '').trim()) {
      try { concernPins = JSON.parse(concernsRaw) || []; } catch (e) {
        Logger.log('Plane sync skipping (bad Nadir Concerns JSON): ' + accountName);
        skipped++; continue;
      }
    }
    try { bounds = boundsRaw ? JSON.parse(boundsRaw) : null; } catch (e) { bounds = null; }

    const baseKey = String(accountName).toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');
    const viewId  = hashId(baseKey + '-plane', creds.hashSalt);
    const hubId   = indexHubId_({
      siteNo: row[PLANE_COL_SITE_NO - 1],
      accountName: accountName,
      address: address,
      salt: creds.hashSalt
    });
    const hoaSlug = slugify(hoaTag);

    const propertyData = {
      name:            accountName,
      address:         address,
      view:            'plane',
      hoa:             hoaSlug || '',
      account_type:    accountType,
      nadir:           { url: nadirUrl,
                         pins: elementPins.concat(concernPins),
                         element_pins: elementPins,
                         concern_pins: concernPins,
                         bounds: bounds },
      alpha:           { url: alphaUrl,   desc: toBullets(alphaDesc)   },
      bravo:           { url: bravoUrl,   desc: toBullets(bravoDesc)   },
      charlie:         { url: charlieUrl, desc: toBullets(charlieDesc) },
      delta:           { url: deltaUrl,   desc: toBullets(deltaDesc)   },
      considerations:  considerations || '',
      clarifications:  clarifications || '',
      viewer360:       viewer360 || ''
    };
    if (!isNaN(lat) && !isNaN(lng)) { propertyData.lat = lat; propertyData.lng = lng; }
    files.push({ path: 'data/plane/' + viewId + '.json', content: JSON.stringify(propertyData, null, 2) });

    // Merge ONLY views.plane onto the satellite site_no hub. Never hash
    // Account Name as the index filename (that forks a second Jones file).
    let mergedViews = { plane: viewId };
    if (hubId) {
      const patch = {
        name: accountName, address, hoa: hoaSlug || '', account_type: accountType,
        views: { plane: viewId }
      };
      if (!isNaN(lat) && !isNaN(lng)) { patch.lat = lat; patch.lng = lng; }
      const up = upsertIndexEntry_(hubId, patch);
      files.push(up.file);
      mergedViews = up.entry.views;
      if (hoaSlug) {
        if (!hoaMap[hoaSlug]) hoaMap[hoaSlug] = { name: hoaTag, properties: [] };
        if (!hoaMap[hoaSlug].properties.includes(hubId)) hoaMap[hoaSlug].properties.push(hubId);
      }
    } else {
      Logger.log('Plane sync: no unique satellite site_no for "' + accountName +
                 '" — published data/plane/' + viewId + '.json, skipped index. Set column AC (Site No).');
    }

    updates.push({ rowIndex: i, id: hubId, viewId: viewId, accountName: accountName, address: address, hoaTag: hoaTag, views: mergedViews });
    processed++;
  }

  if (!files.length) {
    Logger.log('Nothing to push for: ' + PLANE_SHEET);
    SpreadsheetApp.getActiveSpreadsheet().toast('Plane sync: no complete rows to push.');
    return;
  }

  Object.keys(hoaMap).forEach(slug => {
    files.push({ path: 'data/hoa/' + slug + '.json', content: JSON.stringify(hoaMap[slug], null, 2) });
  });

  if (!pushAllToGitHub(files, 'Plane')) {
    SpreadsheetApp.getActiveSpreadsheet().toast('Plane sync: GitHub push FAILED — see execution logs.');
    return;
  }

  updates.forEach(u => {
    if (!u.id) return;
    const viewLink  = VIEWER_BASE_URL + '?property=' + u.id + '&tab=plane';
    const intelLink = VIEWER_BASE_URL + '?property=' + u.id;
    sheet.getRange(u.rowIndex + 1, PLANE_COL_FR_LINK).setValue(viewLink);
    sheet.getRange(u.rowIndex + 1, PLANE_COL_UPLOAD_DATE).setValue(new Date().toLocaleString());
    updateIntelLinksSheet(u.accountName, u.address, intelLink, u.views, u.hoaTag);
  });

  Logger.log('Done [Plane]. Processed: ' + processed + ' | Skipped: ' + skipped);
  SpreadsheetApp.getActiveSpreadsheet().toast('Plane sync: pushed ' + processed + ' properties (' + skipped + ' skipped).');
}

// ── Audits ───────────────────────────────────────────────────────────────────

function checkPlaneAccountNameCollisions() {
  const sheet = SpreadsheetApp.getActiveSpreadsheet().getSheetByName(PLANE_SHEET);
  const data = sheet.getDataRange().getValues();
  const seen = {};
  for (let i = 1; i < data.length; i++) {
    const name = String(data[i][PLANE_COL_ACCOUNT - 1] || '').trim().toLowerCase();
    if (!name) continue;
    if (!seen[name]) seen[name] = [];
    seen[name].push(i + 1);
  }
  Object.keys(seen).forEach(name => {
    if (seen[name].length > 1) {
      Logger.log('COLLISION: "' + name + '" appears on rows: ' + seen[name].join(', '));
    }
  });
  Logger.log('Check complete.');
}

function auditAccountNameMismatches() {
  const ss = SpreadsheetApp.getActiveSpreadsheet();
  const satSheet   = ss.getSheetByName(SATELLITE_SHEET);
  const planeSheet = ss.getSheetByName(PLANE_SHEET);

  // Build address -> account name map from Satellite
  const satData = satSheet.getDataRange().getValues();
  const satByAddress = {};
  for (let i = 1; i < satData.length; i++) {
    const addr = normalizePlaneAddress_(String(satData[i][SAT_COL_ADDRESS - 1] || ''));
    if (addr) satByAddress[addr] = String(satData[i][SAT_COL_ACCOUNT - 1] || '').trim();
  }

  // Compare against Plane sheet, matched by address
  const planeData = planeSheet.getDataRange().getValues();
  let mismatches = 0;
  for (let i = 1; i < planeData.length; i++) {
    const addr = normalizePlaneAddress_(String(planeData[i][PLANE_COL_ADDRESS - 1] || ''));
    const planeName = String(planeData[i][PLANE_COL_ACCOUNT - 1] || '').trim();
    if (!addr || !planeName) continue;
    const satName = satByAddress[addr];
    if (satName && satName.trim().toLowerCase() !== planeName.toLowerCase()) {
      Logger.log('MISMATCH — Plane row ' + (i + 1) + ': Satellite="' + satName + '" vs Plane="' + planeName + '" (address: ' + addr + ')');
      mismatches++;
    } else if (!satName) {
      Logger.log('NO SATELLITE MATCH — Plane row ' + (i + 1) + ': "' + planeName + '" (address: ' + addr + ') — not found on Satellite sheet');
    }
  }
  Logger.log('Audit complete. ' + mismatches + ' name mismatches found.');
}